### PR TITLE
Add the ability to show/hide headers on demand.

### PR DESCRIPTION
**Pull request by raycoarana**
With this little change we could implement our UI that requires to show headers only when searching.

### CODE REVIEW

**Comment by emilsjolander** [comment]
I would rather implement this inside the adapter. An optional method like ?`shouldShowHeaderForPosition(int position)` this allows for more flexibility

**Comment by raycoarana** [comment]
I don't see the use case where you need that flexibility. If you show for position 1, hide por position 2, then item at position 2 will look like be inside the same header as item 1, so its the same as telling the list that items 1 and 2 creates the same header.

**Comment by tomoyuki28jp** [comment]
@emilsjolander 

> I would rather implement this inside the adapter. An optional method like ?shouldShowHeaderForPosition(int position) this allows for more flexibility

`StickyListHeadersAdapter` is an interface. How do you wan to implement this as an optional method inside the adapter?

**Comment by tomoyuki28jp** [comment]
@emilsjolander

I see few people want this feature.
https://github.com/emilsjolander/StickyListHeaders/issues/344
https://github.com/emilsjolander/StickyListHeaders/issues/362

>  just have the lists empty view include the same layout as the first header.
> https://github.com/emilsjolander/StickyListHeaders/issues/232#issuecomment-28728041

I understand what you say, but providing this option like `shouldShowHeaderForPosition` is a bit easier.

**Comment by tomoyuki28jp** [comment]
@emilsjolander

> just have the lists empty view include the same layout as the first header.

I wanna always show my header for a certain position. I cannot use an empty view for the purpose because list might not be empty.

**Comment by patedit** [comment]
I've created a new PR for this feature tracking the problem down using a different approach (i.e. modifying the adapter VS switching between adapters for the `WrapperList`). This'll have some benefits from a UX point of view. Thanks! https://github.com/emilsjolander/StickyListHeaders/pull/453

**Pull request closed without merging**
